package org.desha.app.domain;

public enum PersonType {
    ACTOR,
    PRODUCER,
    DIRECTOR,
    SCREENWRITER,
    DIALOGUE_WRITER,
    MUSICIAN,
    PHOTOGRAPHER,
    COSTUMIER,
    DECORATOR,
    EDITOR,
    CASTER,
    ART_DIRECTOR,
    SOUND_EDITOR,
    VISUAL_EFFECTS_SUPERVISOR,
    MAKEUP_ARTIST,
    HAIR_DRESSER,
    STUNT_MAN
}
