package org.desha.app.domain;

public enum PersonType {
    ACTOR,
    PRODUCER,
    DIRECTOR,
    ASSISTANT_DIRECTOR,
    SCREENWRITER,
    COMPOSER,
    MUSICIAN,
    PHOTOGRAPHER,
    COSTUMIER,
    DECORATOR,
    EDITOR,
    CASTER,
    ARTIST,
    SOUND_EDITOR,
    VFX_SUPERVISOR,
    SFX_SUPERVISOR,
    MAKEUP_ARTIST,
    HAIR_DRESSER,
    STUNT_MAN
}
